In [1]:
import pandas as pd

In [19]:
df =  pd.read_csv('Titanic-Dataset.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [4]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [12]:
df['Age'].head(59)

0     22.0
1     38.0
2     26.0
3     35.0
4     35.0
5      NaN
6     54.0
7      2.0
8     27.0
9     14.0
10     4.0
11    58.0
12    20.0
13    39.0
14    14.0
15    55.0
16     2.0
17     NaN
18    31.0
19     NaN
20    35.0
21    34.0
22    15.0
23    28.0
24     8.0
25    38.0
26     NaN
27    19.0
28     NaN
29     NaN
30    40.0
31     NaN
32     NaN
33    66.0
34    28.0
35    42.0
36     NaN
37    21.0
38    18.0
39    14.0
40    40.0
41    27.0
42     NaN
43     3.0
44    19.0
45     NaN
46     NaN
47     NaN
48     NaN
49    18.0
50     7.0
51    21.0
52    49.0
53    29.0
54    65.0
55     NaN
56    21.0
57    28.5
58     5.0
Name: Age, dtype: float64

## Drop Nan values

In [37]:
df.dropna(subset=['Embarked'], inplace=True)

In [40]:
df['Embarked'].isnull().sum()

0

## fillna() method

In [43]:
mean_age = df['Age'].mean()
print(mean_age)
df['Age'].head(59).fillna(mean_age,inplace=True)

29.64209269662921

In [44]:
df['Age'].isnull().sum()

162

## Imputation

In [67]:
cabin_mode = df['Cabin'].mode()
print(cabin_mode)
# df['Cabin'].head(100).mode()
print(df['Cabin'].head(100).isnull().sum())
mode_df = df['Cabin'].head(100).mode()
df['Cabin'].fillna(mode_df[0],inplace = True)
# df['Cabin'].head(100).isnull().sum()
print(df['Cabin'].head(100))

0    C23 C25 C27
Name: Cabin, dtype: object
0
0      C23 C25 C27
1              C85
2      C23 C25 C27
3             C123
4      C23 C25 C27
          ...
96              A5
97         D10 D12
98     C23 C25 C27
99     C23 C25 C27
100    C23 C25 C27
Name: Cabin, Length: 100, dtype: object

In [71]:
df['Cabin'].iloc[100:].isnull().sum()

0

In [72]:
# df['Cabin'].head(100).isnull().sum()
df['Cabin'].isnull().sum()

0

In [78]:
# df['Age'].iloc[60:118].isnull().sum()
df['Age'].iloc[60:118].isnull().sum()
df['Age'].iloc[60:118].fillna(mean_age,inplace=True)

In [79]:
df['Age'].iloc[60:118].isnull().sum()

0

### One Hot Encoding

In [95]:
ohe = pd.get_dummies(df['Cabin'].iloc[0:20]).astype(int)
ohe

    C103  C123  C23 C25 C27  C85  E46  G6
0      0     0            1    0    0   0
1      0     0            0    1    0   0
2      0     0            1    0    0   0
3      0     1            0    0    0   0
4      0     0            1    0    0   0
5      0     0            1    0    0   0
6      0     0            0    0    1   0
7      0     0            1    0    0   0
8      0     0            1    0    0   0
9      0     0            1    0    0   0
10     0     0            0    0    0   1
11     1     0            0    0    0   0
12     0     0            1    0    0   0
13     0     0            1    0    0   0
14     0     0            1    0    0   0
15     0     0            1    0    0   0
16     0     0            1    0    0   0
17     0     0            1    0    0   0
18     0     0            1    0    0   0
19     0     0            1    0    0   0

## Label Encoding

In [98]:
le = df['Cabin'].astype('category').cat.codes
le

0      62
1      80
2      62
3      54
4      62
       ..
886    62
887    29
888    62
889    59
890    62
Length: 889, dtype: int16